### változók
@protocol = http://
@hostname = localhost
@port = 8000
@host = {{protocol}}{{hostname}}:{{port}}


# ------------  lekérdezése ---------
### get users
get {{host}}/api/queryOsztalynevsor
Accept: application/json

### get users by id
get {{host}}/api/queryOsztalytarsak/Ubul
Accept: application/json

### get users
get {{host}}/api/queryOsztalyOldal/1/6
Accept: application/json
### get users
get {{host}}/api/queryOsztalyOldalSzam/3
Accept: application/json


# ------------  /lekérdezések ---------



### teszt
get {{host}}/api/

### get sports
get {{host}}/api/sports


### get sport by id
get {{host}}/api/sports/2

### post sport
post {{host}}/api/sports
Accept: application/json
Content-Type: application/json

{
    "sportNev": "111"
}

### delete sport by id
delete {{host}}/api/sports/12

### patch sport
patch {{host}}/api/sports/9
Accept: application/json
Content-Type: application/json

{
    "sportNev": "yyy"
}

# ------------  osztalies ---------
### get osztalies
get {{host}}/api/osztalies

### get osztalies by id
get {{host}}/api/osztalies/2

### post osztalies
post {{host}}/api/osztalies
Accept: application/json
Content-Type: application/json

{
    "osztalyNev": "111"
}

### delete osztalies by id
delete {{host}}/api/osztalies/11

### patch sport
patch {{host}}/api/osztalies/10
Accept: application/json
Content-Type: application/json

{
    "osztalyNev": "10a"
}

# ------------ /osztalies ---------


# ------------  diaks ---------
### get diaks
get {{host}}/api/diaks

### get diaks by id
get {{host}}/api/diaks/2

### post diaks
post {{host}}/api/diaks
Accept: application/json
Content-Type: application/json

{
    "osztalyId": 1,
    "nev": "Jenő",
    "neme": true,
    "szuletett": "2018-01-12",
    "helyseg": "Szolnok",
    "osztondij": "5000.00",
    "atlag": 3.5
}

### delete diaks by id
delete {{host}}/api/diaks/8

### patch sport
patch {{host}}/api/diaks/9
Accept: application/json
Content-Type: application/json

{
    "osztalyId": 20,
    "helyseg": "Abony"
}

# ------------ /diaks ---------


# ---- sportolas ----
### get sportolas
get {{host}}/api/sportolas

### get sportolas by id
get {{host}}/api/sportolas/2/2

### post sportolas
POST {{host}}/api/sportolas
Accept: application/json
Content-Type: application/json

{
    "diakokId": 6,
    "sportokId": 7
}

### patch sportolas
PATCH {{host}}/api/sportolas/6/6
Accept: application/json
Content-Type: application/json

{
    "diakokId":6,
    "sportokId": 7
}

### delete sportolas by id
DELETE {{host}}/api/sportolas/6/6
Accept: application/json
Content-Type: application/json
# ---- /sportolas ----